spring.application.name: jedis-cache

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/fastsns"
    username: root
    password: user
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

